web:
    image: stevelasker/worksonmymachine:latest
    environment:
    - SERVER_URLS=http://*:80
lb:
  image: tutum/haproxy
  links:
    - web
  ports:
    - "80:80"
  environment:
    - BACKEND_PORT=80
    - BALANCE=roundrobin
